customhost = "database-1.cilsjzz78xdy.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ngminxiong-employee1"
customregion = "us-east-1"
